//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree_Trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEAL()
        {
            this.PORTFOLIO_LOG = new HashSet<PORTFOLIO_LOG>();
        }
    
        public decimal DEALID { get; set; }
        public string DEAL_TYPE { get; set; }
        public Nullable<decimal> POTFOLIO_ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public string CCY1 { get; set; }
        public string CCY2 { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORTFOLIO_LOG> PORTFOLIO_LOG { get; set; }
        public virtual PORTFOLIO PORTFOLIO { get; set; }
    }
}
