//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree_Trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTFOLIO_LOG
    {
        public decimal LOGID { get; set; }
        public Nullable<decimal> DEALID { get; set; }
        public string DEALTYPE { get; set; }
        public Nullable<int> CURRENTAMOUNT { get; set; }
        public Nullable<int> CHNAGEDAMOUNT { get; set; }
        public Nullable<decimal> PORTFOLIOID { get; set; }
    
        public virtual DEAL DEAL { get; set; }
        public virtual PORTFOLIO PORTFOLIO { get; set; }
    }
}
