//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree_Trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTFOLIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PORTFOLIO()
        {
            this.DEALS = new HashSet<DEAL>();
            this.PORTFOLIO_LOG = new HashSet<PORTFOLIO_LOG>();
        }
    
        public decimal PORTFOLIOID { get; set; }
        public string PORTFOLIOID_NAME { get; set; }
        public Nullable<int> PORTFOLIO_TOTAL_AMOUNT { get; set; }
        public Nullable<System.DateTime> TIMECREATED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEAL> DEALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORTFOLIO_LOG> PORTFOLIO_LOG { get; set; }
    }
}
