
--
-- DEALS
--
  CREATE TABLE "DEALS" 
   (	"DEALID" NUMBER(*,0),
	"DEAL_TYPE" VARCHAR2(20 CHAR),
	"POTFOLIO_ID" NUMBER(38,0),
	"USER_ID" NUMBER(*,0),
	"CCY1" VARCHAR2(45 CHAR),
	"CCY2" VARCHAR2(45 CHAR),
	"RATE" NUMBER(38,2),
	"AMOUNT" NUMBER(10,0),
	"TRADE_DATE" DATE,
	"BANK1" VARCHAR2(20),
	"BANK2" VARCHAR2(20),
	CONSTRAINT "PK1" PRIMARY KEY ("DEALID") ENABLE
   );
--
-- INSERT_DEAL_PORTFOLIOLOG
--
  CREATE OR REPLACE TRIGGER "INSERT_DEAL_PORTFOLIOLOG"
  AFTER INSERT ON "DEALS"FOR EACH ROW
  BEGIN
    INSERT INTO PORTFOLIO_LOG (PORTFOLIOID, DEALID,DEALTYPE)
    VALUES (:new.POTFOLIO_ID, :new.DEALID,:new.DEAL_TYPE);
END;
/
--
-- PK1
--
  CREATE UNIQUE INDEX "PK1" ON "DEALS" ("DEALID");
--
-- FKPORT2
--
ALTER TABLE "DEALS" ADD CONSTRAINT "FKPORT2" FOREIGN KEY ("POTFOLIO_ID") REFERENCES "PORTFOLIOS"("PORTFOLIOID") ENABLE;


	DEALID	DEAL_TYPE	POTFOLIO_ID	USER_ID	CCY1	CCY2	RATE	AMOUNT	TRADE_DATE	BANK1	BANK2
	3	Spot Deal	4	2	EUR	EGP	14.2	31755099	08/13/2019 00:00:00	JBM	JBM
