
--
-- PORTFOLIO_LOG
--
  CREATE TABLE "PORTFOLIO_LOG" 
   (	"LOGID" NUMBER(*,0) NOT NULL ENABLE,
	"DEALID" NUMBER(38,0),
	"DEALTYPE" VARCHAR2(45 CHAR),
	"CURRENTAMOUNT" NUMBER(10,0),
	"CHNAGEDAMOUNT" NUMBER(10,0),
	"PORTFOLIOID" NUMBER(38,0),
	CONSTRAINT "PKLOGID" PRIMARY KEY ("LOGID") ENABLE
   );
--
-- PORTFOLIOLOG_AUTO_INCREMENT
--
  CREATE OR REPLACE TRIGGER "PORTFOLIOLOG_AUTO_INCREMENT"
  BEFORE INSERT ON "PORTFOLIO_LOG"FOR EACH ROW
  BEGIN
    SELECT increment_by_1.NEXTVAL INTO :new.LOGID FROM dual;
END;
/
--
-- PKLOGID
--
  CREATE UNIQUE INDEX "PKLOGID" ON "PORTFOLIO_LOG" ("LOGID");
--
-- FKDEAL
--
ALTER TABLE "PORTFOLIO_LOG" ADD CONSTRAINT "FKDEAL" FOREIGN KEY ("DEALID") REFERENCES "DEALS"("DEALID") ENABLE;

--
-- FKPORT
--
ALTER TABLE "PORTFOLIO_LOG" ADD CONSTRAINT "FKPORT" FOREIGN KEY ("PORTFOLIOID") REFERENCES "PORTFOLIOS"("PORTFOLIOID") ENABLE;



	LOGID	DEALID	DEALTYPE	CURRENTAMOUNT	CHNAGEDAMOUNT	PORTFOLIOID
	1	3	Spot Deal	4000		4