
--
-- PORTFOLIOS
--
  CREATE TABLE "PORTFOLIOS" 
   (	"PORTFOLIOID" NUMBER(*,0) NOT NULL ENABLE,
	"PORTFOLIOID_NAME" VARCHAR2(25 CHAR),
	"PORTFOLIO_TOTAL_AMOUNT" NUMBER(10,0),
	"TIMECREATED" TIMESTAMP(6),
	CONSTRAINT "PK1PORTFOLIO" PRIMARY KEY ("PORTFOLIOID") ENABLE
   );
--
-- PK1PORTFOLIO
--
  CREATE UNIQUE INDEX "PK1PORTFOLIO" ON "PORTFOLIOS" ("PORTFOLIOID");
