
--
-- USERS
--
  CREATE TABLE "USERS" 
   (	"USER_ID" NUMBER NOT NULL ENABLE,
	"FULLNAME" VARCHAR2(30 CHAR),
	"USERNAME" VARCHAR2(30 CHAR),
	"EMAIL" VARCHAR2(50 CHAR),
	"USERROLE" VARCHAR2(10 CHAR),
	"ACTIVEFLAG" NUMBER(10,0),
	"PASSWORD" VARCHAR2(30 CHAR),
	CONSTRAINT "PKK1USERS" PRIMARY KEY ("USER_ID") ENABLE
   );
--
-- PKK1USERS
--
  CREATE UNIQUE INDEX "PKK1USERS" ON "USERS" ("USER_ID");




	USER_ID	FULLNAME	USERNAME	EMAIL	USERROLE	ACTIVEFLAG	PASSWORD
	1	KHALED	1	 	ADMIN	1	1
	2	KHALED	2	 	BUS	0	2
	3	KHALED	3	 	IT	0	3
	999999	lol	asd	asd	Admin		g
	0	lol	asd	ssss	Admin		g